name: CICD

on: workflow_dispatch

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Coling the code from github"
  test:
     runs-on: ubuntu-latest
     steps:
       - name: Test continue
         run: echo "Testing"
         
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deploying the app
         run: echo "Docker compose deploying the app"

            
   
   
  
